# Generated by Django 4.2.25 on 2025-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="tag",
            field=models.CharField(default="untagged", max_length=100),
            preserve_default=False,
        ),
    ]
