# Generated by Django 4.2.25 on 2025-10-02 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("note2webapp", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelupload",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
