# Generated by Django 4.2.25 on 2025-10-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0004_modelupload_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="category",
            field=models.CharField(
                choices=[
                    ("research", "Research"),
                    ("production", "Production"),
                    ("testing", "Testing"),
                ],
                default="research",
                max_length=50,
            ),
        ),
    ]
