# Generated by Django 4.2.25 on 2025-10-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0005_modelversion_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="schema_file",
            field=models.FileField(blank=True, null=True, upload_to="schemas/"),
        ),
    ]
