# Generated by Django 4.2.25 on 2025-10-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0005_modelversion_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelversion",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="modelversion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="schema_file",
            field=models.FileField(blank=True, null=True, upload_to="schemas/"),
        ),
    ]
