# Generated by Django 4.2.25 on 2025-10-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "note2webapp",
            "0006_alter_modelversion_options_modelversion_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="version_number",
            field=models.IntegerField(default=1),
        ),
    ]
