# Generated by Django 4.2.25 on 2025-11-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0007_modelversion_version_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
