# Generated by Django 4.2.25 on 2025-10-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "note2webapp",
            "0006_alter_modelversion_options_modelversion_deleted_at_and_more",
        ),
        (
            "note2webapp",
            "0007_alter_modelversion_options_modelversion_deleted_at_and_more",
        ),
    ]

    operations = []
