# Generated by Django 4.2.25 on 2025-11-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "note2webapp",
            "0010_modelversion_bundle_hash_modelversion_model_hash_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("uploader", "Model Uploader"),
                    ("reviewer", "Model Reviewer"),
                ],
                default="uploader",
                max_length=20,
            ),
        ),
    ]
