# Generated by Django 4.2.25 on 2025-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0012_modelcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this version has been tested."
            ),
        ),
    ]
