# Generated by Django 4.2.25 on 2025-12-13 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("note2webapp", "0015_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="url",
            new_name="verb",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("comment", "Comment"),
                    ("version", "Model Version"),
                    ("model", "Model Upload"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actor_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
